todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todo_id>/delete', views.delete, name='delete'),
    path('<int:todo_id>/update', views.update, name='update'),
    path('add/', views.add, name='add')
]

user_management/urls.py
from . import settings, views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ResetPasswordView, ChangePasswordView

from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls'), name='todos'),
    path('', include('users.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

todos/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta

class Todo(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField('Created', auto_now_add=True)
    update_at = models.DateTimeField('Updated', auto_now=True)
    isCompleted = models.BooleanField(default=False)
    user = models.CharField(max_length=100, default='nouser')
    priority = models.IntegerField(default=0)
    description = models.CharField(default="",max_length=1000)
    duedate = models.DateField(default=timezone.now() + timedelta(1) )

    def __str__(self):
        return self.title

    @property
    def remaining_days(self):
        remaining = (self.duedate - timezone.now().date()).days
        return remaining

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import Todo
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    login_user = request.user
    return render(request, 'todos/index.html', {'todo_list': Todo.objects.filter(user=login_user).order_by('isCompleted','-priority','created_at'), 'user': login_user})


def add(request):
    title = request.POST['title']
    description = request.POST['description']
    priority = request.POST['priority']
    due_date =request.POST['due_date']
    Todo.objects.create(title=title,description=description,priority=priority,duedate=due_date, user=request.user)

    return redirect('todos:index')


def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()

    return redirect('todos:index')


def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    isCompleted = request.POST.get('isCompleted', False)
    if isCompleted == 'on':
        isCompleted = True

    todo.isCompleted = isCompleted

    todo.save()
    return redirect('todos:index')

todos/templates/todos/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--- Our CSS file -->
    <link rel="stylesheet" href="{% static 'css/style.css?v=3' %}">

  {% block title %}
  {% endblock %}
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> <script src="https://kit.fontawesome.com/15974f9624.js" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}

  </body>
</html>

todos/templates/todos/index.html
{% extends 'users/base.html' %}

{% block title %}
Your Task List</title>
{% endblock %}

{% block content %}
<div class="container">

  <!-- title row -->
  <div class="row">
    <div class="offset-md-2 col-lg-9">
      <div class="page-header">
        <h1>
          {{ user }}'s Task List 
        </h1>
        <p>
          It's time to tackle your tasks head-on! Make sure to stay on top of your priorities! 🚀  
          <br>What do you want to accomplish today? Let's get to work! 💪
        </p>
      </div>
    </div>
  </div>

  <!-- Add a todo row -->
  <div class="row">
    <div class="offset-md-2 col-lg-9">
      <form method="post" action="{% url 'todos:add' %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6 mb-2">
            <input type="text" class="form-control" name="title" placeholder="Accomplish..." required>
          </div>
          <div class="col-md-12 mb-2">
            <textarea class="form-control" name="description" placeholder="Description (optional)"></textarea>
          </div>
          <div class="col-md-6 mb-2">
            <label for="due_date">Due Date:</label>
            <input type="date" class="form-control" name="due_date" placeholder="Due date">
          </div>
          <div class="col-md-6 mb-2">
            <label for="priority">Priority (optional):</label>
            <select class="form-control" name="priority">
              <option value="2">High</option>
              <option value="1">Medium</option>
              <option value="0" selected="true">Low</option>
            </select>
          </div>
          <div class="col-md-6">
            <button type="submit" name="submit" class="btn btn-outline-primary">
              Add
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <hr />

  <!-- todo list row -->
  <div class="row">
    <div class="offset-md-2 col-lg-6">
      <div class="list-group">
        {% for todo in todo_list %}
        <div class="list-group-item {% if todo.isCompleted %} todo-complete {% endif %}"
        {% if todo.priority == 1 %}
        style="background: yellow; color: black"
        {% elif todo.priority == 2 %}
        style="background: orange; color: black"
        {% endif %}
        {% if todo.description %} data-tooltip="{{ todo.description }}"{% endif %}
        >
          <form style="display: inline;" method="post" action="{% url 'todos:update' todo.id %}">
            {% csrf_token %}
            <input type="checkbox" name="isCompleted" onchange="this.form.submit()" {% if todo.isCompleted %} checked
              {% endif %} class="todo-status-checkbox"
              title="{% if not todo.isCompleted %} mark as done {% else %} mark undone {% endif %}">
          </form>
          {{ todo.title }}
          {% if todo.remaining_days %} |  Due in {{ todo.remaining_days }} day(s) {% endif %}
          
          <a href="{% url 'todos:delete' todo.id %}" title="Delete">
            <i class="far fa-trash-alt"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}